### PR TITLE
Fix conversion roundtrip tests

### LINKED ISSUE #202: `test_f32_to_i32_exhaustive` fails in v0.4
The test takes a long time and hasn't been run on CI.

```
failures:

---- test_f32_to_i32_exhaustive_sse4 stdout ----

thread 'test_f32_to_i32_exhaustive_sse4' (153003) panicked at fearless_simd_tests/tests/mod.rs:79:17:
assertion `left == right` failed: f32x4::to_int::<i32x4<_>>() returns the same results as Rust's `as i32`
  left: [-2147483648, -2147483648, -2147483648, -2147483648]
 right: [2147483647, 2147483647, 2147483647, 2147483647]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_f32_to_i32_exhaustive_avx2 stdout ----

thread 'test_f32_to_i32_exhaustive_avx2' (153001) panicked at fearless_simd_tests/tests/mod.rs:79:17:
assertion `left == right` failed: f32x4::to_int::<i32x4<_>>() returns the same results as Rust's `as i32`
  left: [-2147483648, -2147483648, -2147483648, -2147483648]
 right: [2147483647, 2147483647, 2147483647, 2147483647]

---- test_f32_to_u32_exhaustive_sse4 stdout ----

thread 'test_f32_to_u32_exhaustive_sse4' (153006) panicked at fearless_simd_tests/tests/mod.rs:103:17:
assertion `left == right` failed: f32x4::to_int::<u32x4<_>>() returns the same results as Rust's `as u32`
  left: [0, 0, 0, 0]
 right: [4294967295, 4294967295, 4294967295, 4294967295]

---- test_f32_to_u32_exhaustive_avx2 stdout ----

thread 'test_f32_to_u32_exhaustive_avx2' (153004) panicked at fearless_simd_tests/tests/mod.rs:103:17:
assertion `left == right` failed: f32x4::to_int::<u32x4<_>>() returns the same results as Rust's `as u32`
  left: [0, 0, 0, 0]
 right: [4294967295, 4294967295, 4294967295, 4294967295]
```

### PR DESCRIPTION
**Pull request by Shnatsel**
Update exhaustive tests to roundtrip precise conversions on all values; out-of-range values are intentionally implementation-defined in the non-precise variants.

Add tests for the non-precise variants that correctly ignore the out-of-range values.

Fixes #202

### CODE REVIEW

File: fearless_simd_tests/tests/mod.rs [hunk 1]
```diff
@@ -98,11 +122,49 @@ fn test_f32_to_u32_exhaustive<S: Simd>(simd: S) {
...
+                    "f32x4::to_int::<u32x4<_>>() returns the same results as Rust's `as u32` (input: {:?})", floats.as_slice()
+                );
+            }
+        },
+    );
+}
+
+#[simd_test]
+#[ignore]
+fn test_f32_to_i32<S: Simd>(simd: S) {
```
Comment (tomcur) [inline fearless_simd_tests/tests/mod.rs]: Should this also be called `_exhaustive`?

```suggestion
fn test_f32_to_i32_exhaustive<S: Simd>(simd: S) {
```

**Review by tomcur — APPROVED** [review]
